#https://github.com/SeleniumHQ/docker-selenium
version: "3"
services:
    selenium-hub:
        image: selenium/hub:3.141.59-mercury
        container_name: selenium-hub
        environment:
            - GRID_TIMEOUT=0
            - GRID_BROWSER_TIMEOUT=0
        ports:
            - "4444:4444"
    chrome_1:
        image: selenium/node-chrome-debug:3.141.59-mercury
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - VNC_NO_PASSWORD=1
            - NODE_MAX_INSTANCES=99
            - NODE_MAX_SESSION=99
            - HUB_PORT=4444
        ports:
            - "5900:5900"
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=python_manage
        ports:
            - "5432:5432"